# Generated by Django 2.2.3 on 2020-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Title of News', max_length=5000, unique=True)),
                ('image', models.CharField(help_text='Url of News Image', max_length=6000)),
                ('link', models.CharField(help_text='Link of news', max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
