# Generated by Django 2.2.3 on 2020-03-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default='', help_text='Url of News Image', max_length=6000),
        ),
    ]
