# Generated by Django 2.2.3 on 2020-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='State', max_length=250, unique=True)),
                ('number_confirmed', models.IntegerField(help_text='Number of confirmed coronavirus cases', max_length='1000')),
            ],
        ),
    ]
