# Generated by Django 2.2.3 on 2020-04-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_statesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statesinfo',
            name='number_confirmed',
            field=models.IntegerField(help_text='Number of confirmed Coronavirus cases'),
        ),
    ]
