# Generated by Django 2.2.3 on 2020-04-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200403_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='NigeriaSummaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Nigeria', help_text='Country', max_length=250, unique=True)),
                ('total_tested', models.CharField(help_text='Total Number of People Tested', max_length=50)),
                ('number_confirmed', models.IntegerField(help_text='Number of confirmed Coronavirus cases')),
                ('total_recovered', models.IntegerField(help_text='Number of confirmed Coronavirus recovered ')),
                ('total_deaths', models.IntegerField(help_text='Number of confirmed Coronavirus deaths')),
                ('total_active', models.IntegerField(help_text='Number of confirmed active Coronavirus cases')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='statesinfo',
            name='total_active',
            field=models.IntegerField(default=0, help_text='Number of confirmed active Coronavirus cases'),
        ),
        migrations.AddField(
            model_name='statesinfo',
            name='total_deaths',
            field=models.IntegerField(default=0, help_text='Number of confirmed Coronavirus deaths'),
        ),
        migrations.AddField(
            model_name='statesinfo',
            name='total_recovered',
            field=models.IntegerField(default=0, help_text='Number of confirmed Coronavirus recovered'),
        ),
    ]
